server:
  port: 8083

spring:
  application:
    name: examen-service
  datasource:
    url: jdbc:mysql://localhost:3306/examen_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true

  # Keycloak / OAuth2 Resource Server Configuration (Spring Boot 3 standard)
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/esprit-realm
          jwk-set-uri: http://localhost:8080/realms/esprit-realm/protocol/openid-connect/certs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# Exposed Actuator Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
